spring.application.name=itctc
server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=itctc;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
jwt.secret=MzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw
jwt.expiration=86400000

# Selfies and attached documents path
inspection.upload.selfies=/home/Synergiz/uploads/selfies
inspection.upload.documents=/home/Synergiz/uploads/documents

# Maximum size of a single uploaded and Total upload  
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
